version: "3.9"  
services:
  app:
    container_name: persistence-example
    image: maeddes/persistence-example:v0.1
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/mydb
    depends_on: 
      - database
#    networks:  
#      - mynetwork
    # restart: true
  database:
    container_name: postgresdb
    image: postgres:latest
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_DB=mydb
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=matthias
#    networks:  
#      - mynetwork
    volumes:
      - /tmp/postgres:/var/lib/postgresql/data

#networks:
#  mynetwork:
#    external: true